### ISSUE TITLE
Scoreboard should use hubot brain

### ISSUE THREAD

**Issue by TerribleDev** [brianchitester/studbot#5]
Right now the Scoreboard uses in memory arrays which won't work if/when the process restarts. You should use the hubot brain api to save the data.

https://github.com/github/hubot/blob/master/docs/scripting.md

**Comment by TerribleDev** [comment]
@brianchitester 

``` javascript
var score = robot.brain.get('scoreBoard');
score.doSomething = "doing something..boilerplate here";
robot.brain.set('scoreBoard', score)
```

**Comment by dggriffin** [comment]
My latest pull request should resolve this.

**Comment by TerribleDev** [comment]
@dggriffin you can reference Issues from PR's so you don't have to comment
